import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import ThemeProvider from '@/components/providers/ThemeProvider';
import LanguageProvider from '@/components/providers/LanguageProvider';
import { Toaster } from "@/components/ui/sonner"
import TopLoadingBar from '@/components/layouts/TopLoadingBar';
import CallCenterProviderWrapper from '@/components/providers/CallCenterProviderWrapper';
import OfflineOverlay from '@/components/shared/OfflineOverlay';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Omni Ai Flow",
  description: "Generated by hodinovy maznel",
};

export default function RootLayout({ children }) {
  return (
    <html 
      lang="en" 
      suppressHydrationWarning
      style={{ margin: 0, padding: 0, width: '100%', maxWidth: '100vw', overflowX: 'hidden' }}
    >
      <head>
        {/* ✅ Prevent Google Translate from automatically translating the page */}
        <meta name="google" content="notranslate" />
        <meta httpEquiv="Content-Language" content="en" />
        {/* ✅ Apply theme before React hydrates to prevent hydration mismatch */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  // Prevent Google Translate
                  if (window.google && window.google.translate) {
                    window.google.translate.TranslateElement = function() {};
                  }
                  
                  // Get theme from localStorage
                  const themeStorage = localStorage.getItem('theme-storage');
                  let theme = 'light';
                  
                  if (themeStorage) {
                    try {
                      const parsed = JSON.parse(themeStorage);
                      theme = parsed.state?.theme || 'light';
                    } catch (e) {
                      theme = 'light';
                    }
                  }
                  
                  // Apply theme
                  const root = document.documentElement;
                  if (theme === 'system') {
                    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                    if (prefersDark) {
                      root.classList.add('dark');
                    } else {
                      root.classList.remove('dark');
                    }
                  } else if (theme === 'dark') {
                    root.classList.add('dark');
                  } else {
                    root.classList.remove('dark');
                  }
                  
                  // Apply cached accent colors to prevent FOUC
                  var accentCache = localStorage.getItem('accent-color-cache');
                  if (accentCache) {
                    try {
                      var accent = JSON.parse(accentCache);
                      var isDark = root.classList.contains('dark');
                      var vars = isDark ? accent.dark : accent.light;
                      if (vars) {
                        Object.keys(vars).forEach(function(key) {
                          root.style.setProperty(key, vars[key]);
                        });
                      }
                      // Set gradient data attribute if this is a gradient preset
                      if (accent.type === 'gradient') {
                        root.setAttribute('data-accent-gradient', 'true');
                      }
                    } catch (ae) {}
                  }

                  // Language is always English for now
                  root.lang = 'en';
                } catch (e) {
                  // Silently fail if localStorage is not available
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
          <ThemeProvider>
            <LanguageProvider>
              <TopLoadingBar />
              <ReactQueryProvider>
                <CallCenterProviderWrapper>
                  {children}
                </CallCenterProviderWrapper>
                <OfflineOverlay />
                <Toaster />
              </ReactQueryProvider>
            </LanguageProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
